### ISSUE TITLE
Python 3.5 Compatibility

### ISSUE THREAD

**Issue by t-spencer** [josephernest/talktalktalk#1]
dumbdbm and several other things in the code have undergone changes from Python 2 to 3, could be updated. Would be interested in helping with this! Could easily have a 2 and 3 version in the repo.

**Comment by josephernest** [comment]
I'll update a few things now in a few minutes. Then it would be interesting to have a code that works with both 2 and 3 :) 
Thanks in advance.

**Comment by t-spencer** [comment]
Awesome! 2to3 should save you a bit of work, I've gotten my altered version working already. Thanks!

**Comment by josephernest** [comment]
I just did a commit right now. If you want to use it to do a py2+3 version, that would be awesome. Can you do a pull requst?

**Comment by josephernest** [comment]
@t-spencer I did a few commits the last days. Would you share a Python3 version as a pull request, and I'll merge it?

**Comment by t-spencer** [comment]
Gladly! I don't have the code with me, but I'll get to it when I return to work on Tuesday

**Comment by josephernest** [comment]
Great! Maybe can you do the same processing on the current state of the code? Thanks in advance!

**Comment by Jpchoulet** [comment]
I there, I am looking for the code with Python 3.5 Compatibility? Thanks!

**Comment by josephernest** [comment]
Hi! I haven't really used Python 3 yet... Still on 2.7 I have to admit...
I won't have time to do tests or try Python 3.5 these days. Feel free to do a fork that supports it, and I'll mention it.
