### ISSUE TITLE
Multiple users with the same nickname and error when special characters in nickname

### ISSUE THREAD

**Issue by skorotkiewicz** [josephernest/talktalktalk#15]
Users may have at the same time the same nickname and error when entering special characters in nickname "Your username has been changed because the one you entered is reserved."

**Comment by josephernest** [comment]
Yes it is possible. Nothing has been added in code to prevent multiple users to have the same username.

About usernames, yes, that's done on purpose, it's explained [here](https://github.com/josephernest/talktalktalk/issues/9).

Remember that the goal of this small chat is to be super light, easy to install, and to be used inside a small team, it's not designed to be malicious-user proof!
