### ISSUE TITLE
Only "Click anywhere or press any key to reload the page."

### ISSUE THREAD

**Issue by skorotkiewicz** [josephernest/talktalktalk#4]
You can not add new messages, all the while bearing the message: "Click anywhere or press any key to reload the page."
http://talk.itunix.eu/

**Comment by skorotkiewicz** [comment]
Okay, i know why.
Talktalktalk dosent work with apache         
ProxyPass / http://127.0.0.1:9000/
ProxyPassReverse / http://127.0.0.1:9000/

**Comment by josephernest** [comment]
It does work with Apache 2.4.  You also need to enable 2 modules :

>  If it doesn't, try to run `a2enmod proxy proxy_wstunnel ; service apache2 restart` to enable WebSocket handling by Apache.

Does it work?

**Comment by skorotkiewicz** [comment]
Okay, it works. Thanks!

**Comment by josephernest** [comment]
Did you need ProxyPassReverse or were my commands enough to solve it?
