### ISSUE TITLE
Prevent ul, li, blockquote to be used in username / message

### ISSUE THREAD

**Issue by josephernest** [josephernest/talktalktalk#6]
Does anyone know how to configure `bleach` to do this ?

**Comment by colwin** [comment]
bleach.clean() with a custom list of tags should be able to do this? I can take a stab at this if you'd like

**Comment by josephernest** [comment]
Oh yes please if you can have a look it would be nice...

**Comment by colwin** [comment]
Cool. Working on it. Will send you a PR soon.
